### PR TITLE
issue #18 fix filter logic

### LINKED ISSUE #18: Filter logic doesn't work as expected
The filters bar in the website

If you select two units in the Unit section, it works as expected with the OR logic (i.e., selecting Unit 2 and Unit 3 shows resources tagged as either Unit 2 or Unit 3). But if you select across categories, it still uses the OR logic (i.e., selecting Unit 2 and Worksheet shows resources tagged as Unit 2 or Worksheet -- not the Worksheets in Unit 2). I think that (selecting across categories) should use AND logic. Or, design the filter so that teachers can do either.

### PR DESCRIPTION
**Pull request by Isabel-S**
uses OR for within a tag category, AND for between tag categories
if no filters are selected, it is assumed that all tags are selected

### CODE REVIEW

**Comment by parthsarin** [comment]
What happens if you have a resource with no tags? Does it show up? (assuming all filters are checked might mean that things with no tags don’t show up)

File: src/Dashboard/Resources/Filter/Filter.tsx [hunk 1]
```diff
@@ -1,99 +1,114 @@
-import React, { useState, useEffect } from 'react';
+import { useState, useEffect } from 'react';
 
 interface Props {
-  onUpdate: (tags: string[]) => void;
+  onUpdate: (tags: string[], count: {'unit': number, 'type': number}) => void;
 }
 
-const Filter = ({ onUpdate }: Props) => {
+let prevTags = [''];
```
Comment (parthsarin) [inline src/Dashboard/Resources/Filter/Filter.tsx]: Since this is a global variable it interferes with renders — can you convert it to a state variable? See this screenshot — the SearchBar is re-rendered in a flow where I just clicked on the checkboxes

Screenshot 2023-05-09 at 10 40 55 AM

File: src/Dashboard/Resources/Filter/Filter.tsx [hunk 2]
```diff
@@ -1,99 +1,114 @@
...
 
+const Filter = ({ onUpdate }: Props) => {
   const [selectedTags, setSelectedTags] = useState(['']);
+  const [selectedTagsCount, setSelectedTagsCount] = useState({'unit': 0, 'type': 0})
 
-  const handleTagSelect = (tag: string) => {
+  const handleTagSelect = (tag: string, tagClass: string|null) => {
```
Comment (parthsarin) [inline src/Dashboard/Resources/Filter/Filter.tsx]: Instead of inferring whether something is checked (which could get messed up if they get out of sync) — consider using `event.currentTarget.checked` instead

File: src/Dashboard/Resources/Filter/Filter.tsx [hunk 3]
```diff
@@ -1,99 +1,114 @@
...
 
   useEffect(() => {
-    onUpdate(selectedTags);
+    if (prevTags !== selectedTags) {
+      prevTags = selectedTags;
+      onUpdate(selectedTags, selectedTagsCount);
+    }
   });
 
   return (
```
Comment (parthsarin) [inline src/Dashboard/Resources/Filter/Filter.tsx:46]: Can you use a `useMemo` and `useEffect` hook to compute which filters we need to add here instead of putting them in manually? That way as we add more units, more resource types, we won't need to edit this file.

File: src/Dashboard/Resources/Filter/Filter.tsx [hunk 4]
```diff
@@ -1,99 +1,114 @@
...
 
-  const handleTagSelect = (tag: string) => {
+  const handleTagSelect = (tag: string, tagClass: string|null) => {
     const isTagSelected = selectedTags.includes(tag);
 
     if (isTagSelected) {
       setSelectedTags(selectedTags.filter((t) => t !== tag));
+      if (tagClass === 'unit' || tagClass === 'type') {
+        let newTagCount = selectedTagsCount;
+        newTagCount[tagClass] -= 1;
```
Comment (parthsarin) [inline src/Dashboard/Resources/Filter/Filter.tsx:26]: This is a cool way of keeping track of this!

File: src/Dashboard/Resources/Resources.tsx [hunk 5]
```diff
@@ -28,7 +28,9 @@ const defaultResources: Resource[] = [
         name: "Curriculum",
       },
     ],
-    tags: ["Unit 2: AI & You", "Worksheet", "Video"],
+    unitTags: ["Unit 2: AI & You"],
+    typeTags: ["Worksheet", "Video"],
+    miscTags: []
   },
   {
     title: "“What the world looks like to an algorithm” YouTube Video",
```
Comment (parthsarin) [inline src/Dashboard/Resources/Resources.tsx]: I'm a little worried that we're going to have to rewrite all this code if we want to add additional filters. Danielle, for example, was wondering if we could add a filter for `age` or for the `materials` that students might need. Ideally, we'd have this as

```js
tags: {
    "unit": ["Unit 2: AI & You"],
    "type": ["Worksheet", "Video"]
}
```

and then the logic above would use the `keys` of the `tags` variable, instead of hardcoding unit and type.

**Review by parthsarin — CHANGES_REQUESTED** [review]
This is great, thank you for taking this issue. Based on the feedback we're getting from teachers, we may need to add more filter categories (e.g., "age", "materials needed", etc.) so we should try to avoid hardcoding categories (both in the filter UI and in the `defaultResources` object).

File: src/Dashboard/Resources/Filter/Filter.tsx (hunk 4 above)
Comment (Isabel-S) [reply src/Dashboard/Resources/Filter/Filter.tsx:26]: :D

File: src/Dashboard/Resources/Filter/Filter.tsx (hunk 3 above)
Comment (Isabel-S) [reply src/Dashboard/Resources/Filter/Filter.tsx:46]: not sure what this means but I edited files so that the only hardcoded tagNames is in the Resources.ts file as variables

```
interface Resource {
  title: string;
  description: string;
  img: string;
  subLinks: ResourceSubLink[];
  tags: {
    unit: string[],
    type: string[],
    misc: string[]};
  rating?: number;
}

interface ResourceSubLink {
  name: string;
  url: string;
}

const tagNames = ['unit', 'type', 'misc']
```

**Review by parthsarin — APPROVED** [review]
